### ISSUE TITLE
Error while running using CPU

### ISSUE THREAD

**Issue by TheurgicDuke771** [DebadityaPal/RoBERTa-NL2SQL#2]
Hi,
I was trying to run the code in my personal machine (without GPU). So  I changed all
 `device = torch.device("cuda")` to `device = torch.device("cpu")` 
after doing so infer the existing model.pt works. 
But got the bellow error while try to train the model ftom scratch

> D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\python.exe D:/MySpace/PycharmProjects/RoBERTa-NL2SQL/Train.py
  0%|          | 0/7045 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/MySpace/PycharmProjects/RoBERTa-NL2SQL/Train.py", line 42, in <module>
    acc_train = dev_function.train( seq2sql_model, roberta_model, model_optimizer, roberta_optimizer, tokenizer, configuration, path_wikisql, train_loader)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\dev_function.py", line 36, in train
    for batch_index, batch in enumerate(tqdm(train_loader)):
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\site-packages\tqdm\notebook.py", line 253, in __iter__
    for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\site-packages\tqdm\std.py", line 1166, in __iter__
    for obj in iterable:
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\MySpace\PycharmProjects\RoBERTa-NL2SQL\envs\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_data.<locals>.<lambda>'
Process finished with exit code 1

Can you tell me if it is related to gpu/cpu or something else.

**Comment by DebadityaPal** [comment]
Hi @TheurgicDuke771 , thank you for bringing this to my notice. Could you please tell me the Operating System you are using when you run these files?

**Comment by TheurgicDuke771** [comment]
Hi @DebadityaPal, I'm using windows 10 home, And running it in an anaconda env with python 3.6.9, torch 1.7.1

**Comment by DebadityaPal** [comment]
Hey @TheurgicDuke771 , sorry for the late reply. This problem seems to be coming from the Python multiprocessing library. Apparently, the pool function doesn't work properly in windows in certain circumstances. You could refer to [this stackoverflow answer](https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function). It is not related to your CPU/GPU. If possible try running the code in a Linux environment.

**Comment by DebadityaPal** [comment]
@TheurgicDuke771 I am closing this issue for now. If you have any further queries, feel free to contact me.
